version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task-tracker-project
    ports:
      - '5438:5432'
    volumes: 
      - db:/var/lib/postgresql/data